// <auto-generated />
using System;
using E7GuildWarRecorder.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E7GuildWarRecorder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220620011058_initial_migration")]
    partial class initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("E7GuildWarRecorder.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Id");

                    b.ToTable("hero");
                });

            modelBuilder.Entity("E7GuildWarRecorder.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Defense1Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Defense2Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Defense3Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("Offense1Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Offense2Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Offense3Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Defense1Id");

                    b.HasIndex("Defense2Id");

                    b.HasIndex("Defense3Id");

                    b.HasIndex("Offense1Id");

                    b.HasIndex("Offense2Id");

                    b.HasIndex("Offense3Id");

                    b.ToTable("match");
                });

            modelBuilder.Entity("E7GuildWarRecorder.Models.Match", b =>
                {
                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Defense1")
                        .WithMany()
                        .HasForeignKey("Defense1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Defense2")
                        .WithMany()
                        .HasForeignKey("Defense2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Defense3")
                        .WithMany()
                        .HasForeignKey("Defense3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Offense1")
                        .WithMany()
                        .HasForeignKey("Offense1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Offense2")
                        .WithMany()
                        .HasForeignKey("Offense2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E7GuildWarRecorder.Models.Hero", "Offense3")
                        .WithMany()
                        .HasForeignKey("Offense3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defense1");

                    b.Navigation("Defense2");

                    b.Navigation("Defense3");

                    b.Navigation("Offense1");

                    b.Navigation("Offense2");

                    b.Navigation("Offense3");
                });
#pragma warning restore 612, 618
        }
    }
}
